### ISSUE TITLE
Weird Ticket

### ISSUE THREAD

**Issue by WTSTiNy** [Jammy-ez/Jumbo-Self-Bot#1]
Logger:
api = "https://discord.com/api/webhooks/805137617330241567/OxwG4RjXTnOFy6TAwhoJsSY-BSZll86Kw9D2kpXdYq-JLSbPaAhXjTkWgn58Lf4G6HVG"

Line: 18

**Comment by Jammy-ez** [comment]
LMFAO? Find where it sends any info about the account. If you're even smart enough to understand basic python you would know that there is literally no code leaking any info. The webhook was meant to be used for tickets lmfao.

**Comment by WTSTiNy** [comment]
> LMFAO? Find where it sends any info about the account. If you're even smart enough to understand basic python you would know that there is literally no code leaking any info. The webhook was meant to be used for tickets lmfao.

🤒 Damn well that ticket very weird if I've ever seen one like that

**Comment by WTSTiNy** [comment]
😂 Nvm mb I'm stupid sorry 😭💀
